/*
  Warnings:

  - The values [ADEMHALING,LOKALE_REACTIE,ANAFYLAXIE,VERSTUIKING,RADIOGRAFIE,BEWUSTZIJNSVERLIES,FLAUWTE_SYNCOPE,EPILEPSIE,EIGEN_MEDICATIE,HOOFDPIJN,INSECTENBEET,ONTSTEKING,ALCOHOL,DRUGS,KEELPIJN,OOGLETSEL,TANDPIJN,PLEISTER,MAANDVERBAND,ZONNECREME_AFTERSUN] on the enum `ChiefComplaint` will be removed. If these variants are still used in the database, this will fail.

*/
-- AlterEnum
BEGIN;
CREATE TYPE "ChiefComplaint_new" AS ENUM ('HUIDWONDE', 'BRANDWONDE', 'HECHTING', 'ALLERGIE', 'ZONNEALLERGIE', 'PIJN', 'HOODPIJN', 'SPIERPIJN', 'MENSTRUATIEPIJN', 'HYPERVENTILATIE', 'HARTKLACHTEN', 'MAAG_DARM', 'BOVENSTE_LUCHTWEGEN', 'FLAUWTE', 'INTOXICATIE', 'BEWEGINGSSTELSEL', 'BEELDVORMING', 'OOG', 'ANDERE');
ALTER TABLE "PatientEncounter" ALTER COLUMN "chiefComplaint" TYPE "ChiefComplaint_new" USING ("chiefComplaint"::text::"ChiefComplaint_new");
ALTER TYPE "ChiefComplaint" RENAME TO "ChiefComplaint_old";
ALTER TYPE "ChiefComplaint_new" RENAME TO "ChiefComplaint";
DROP TYPE "ChiefComplaint_old";
COMMIT;
